config/routes.rb
Rails.application.routes.draw do
  resources :listings
  root 'statics#home'
  post '/spam', to: 'statics#spam'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  validates :name, :price, :presence => true

  enum room_type: [:undefined, :shared_room, :private_room, :entire_home]

  def self.options_for_location
    ['Kuala Lumpur', 'Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis', 'Pulau Pinang', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu', 'W.P. Labuan', 'W.P. Putrajaya']
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :listings

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    if signed_out?
      flash[:info] = 'Please sign in first'
      redirect_to '/' and return
    end

    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    if @listing.save
      flash[:success] = "Successfully added a new listing!"
      redirect_to '/'
    else
      flash[:danger] = @listing.errors.full_messages.join(', ')
      redirect_to '/'
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :location, :price)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end

  def spam
    @email = params[:email]
    UserMailer.welcome_email(@email).deliver_now
    redirect_to root_url, notice: "Sent a spam to #{@email}"
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to '/'
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairbnbDemo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Home', root_url, class: "navbar-brand" %>
        </div>
        <% if signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">Signed in as <a href="#" class="navbar-link"><%= link_to current_user.email, edit_user_path(current_user) %></a></p>
            </li>
            <li><%= button_to 'Sign out', sign_out_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Sign in', sign_in_path %></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div id="flash">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-container">
    <!-- Name -->
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <!-- Location Dropdown -->
    <div class="form-group">
      <%= f.label :location %>
      <%= f.select :location, Listing.options_for_location, {}, { class: "form-control" } %>
    </div>
    <!-- Room Type Dropdown -->
    <div class="form-group">
      <%= f.label :room_type %>
      <%= f.select :room_type, Listing.room_types, {}, { class: "form-control" } %>
    </div>
    <!-- Price -->
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <!-- Submit Button -->
    <div class="actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listings</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.location %></td>
        <td><%= listing.price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @listing.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/statics/_spam.html.erb
<div class="form-container">
  <%= form_tag('/spam') do %>
    <div class="form-group">
      <%= text_field_tag 'email' %>
    </div>
    <%= submit_tag 'Spam!' %>
  <% end %>
</div>

app/views/statics/home.html.erb
<h1> Welcome to AirBnB Clone </h1>
<h6 style="color:#B2B4B4;"> Please don't sue me </h6>
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <p> Feel in the form to create new listing! </p>
      <%= render 'listings/form', listing: Listing.new %>
      <div style="border:solid 1px #C8C8C8; padding:12px; width:300px;">
      <p> Feel free to spam someone an email! </p>
      <%= render 'spam' %>
      </div>
    </div>
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% Listing.all.each do |l| %>
            <tr>
              <td><%= l.name %></td>
              <td><%= l.location %></td>
              <td><%= l.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
  <%= form_for @user do |f| %>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.submit %>
  <% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>